- name: kuberlab
  charts:
    - name: test-image
      src: https://github.com/nmakhotkin/test_repo
      version: ^1.0.0
      clusters:
        - master-test
      configuration:
        file: values.yaml
        values:
          name: test-from-values
