- charts:
  - clusters:
    - master-test
    configuration:
      file: values.yaml
      values:
        Image:
          kuberlab.io/image:
            CandidateTag: ^0.3.0
            Name: nmakhotkin/test
            Tag: 0.3.0
        name1: test-from-values
    name: test-image
    src: https://github.com/nmakhotkin/test_repo/charts/test-image
    version: ^1.0.0
  global:
    name: test-from-global
  name: kuberlab
- charts:
  - clusters:
    - master-test
    configuration: {}
    name: demo-web-server
    order: 1
    src: https://github.com/kuberlab/demo-web-server/Chart
    version: ^2.0.0
  name: app2
- charts:
  - clusters:
    - master-test
    configuration:
      values:
        Component: demo-server
        CpuLimits: 100m
        CpuRequests: 25m
        Image:
          Name: kuberlab/demo-web-server
          Tag: latest
        MemoryLimits: 64Mi
        MemoryRequests: 64Mi
        Name: demo
        Replicas: 2
        ServerVersion: 1.1.2
    name: demo-web-server
    src: https://github.com/kuberlab/demo-web-server/Chart/
    version: 2.0.1
  name: app_test
