- name: kuberlab
  clusters:
    - master-test
  charts:
    - name: test-image
      src: https://github.com/nmakhotkin/test_repo
      version: 0.2.0
      configuration:
        file: reference to values
        values:
          p1: test
