- charts:
  - clusters:
    - storage-test
    configuration: {}
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/chart/
    version: 1.0.0
  name: monitoring
- charts:
  - clusters:
    - storage-test
    configuration:
      values:
        image: wernight/codiad:alpine
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          logdir: /notebooks/log_dir
          nfs:
            path: /kuberlab
            server: 10.240.0.5
          size: 16Gi
          storageClass: standard
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        serviceType: LoadBalancer
    name: codiad
    src: https://github.com/monstarnn/codiad-chart/
    version: 0.0.1
  - clusters:
    - storage-test
    configuration:
      values:
        image: wernight/codiad:alpine
        persistence:
          accessMode: ReadWriteMany
          data_dir: /data
          enabled: true
          nfs:
            path: /kuberlab
            server: 127.0.0.1
          size: 16Gi
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        serviceType: LoadBalancer
    name: codiad
    src: https://github.com/monstarnn/codiad-chart/
    version: 0.0.1
  name: codiad
