- name: kuberlab
  charts:
    - name: test-image
      src: https://github.com/nmakhotkin/test_repo
      version: 0.2.0
      clusters:
        - master-test
      configuration:
        file: values.yaml
        values:
          p1: test
